### ISSUE TITLE
Typo Chapter 5

### ISSUE THREAD

**Issue by slaurie** [rafalab/dsbook#1]
**Chapter 5, Exercise 1**
I believe the formula should be n(n+1)/2, rather than as shown below.

What is the sum of the first 100 positive integers? There is a formula that tells us the sum of integers 1 through n. It is n(n−1)/2. Define n=100 and then use R to compute the sum of 1 through 100 using the formula. What is the sum?

**Chapter 7, Exercise 11**
I believe you mean "to force an integer" here.

The class of class(a<-1) is numeric not integer. R defaults to numeric and to force a number, you need to add the letter L. Confirm that the class of 1L is integer.

**Comment by rafalab** [comment]
Thanks. I fixed the Rmds. Next time I compile the book the html will get fixed as well.

**Comment by slaurie** [comment]
My bad. Sorry about that. Book is excellent - thanks for your ongoing dedication to open source./science.

**Comment by rafalab** [comment]
No need to apologies. You caught the mistake. Thanks for reporting.
