### ISSUE TITLE
Chapter 2.4.5. Factors: slight confusion around default order of levels

### ISSUE THREAD

**Issue by larswestvang** [rafalab/dsbook#112]
In the introduction to Factors (2.4.5), it says that "The default is for the levels to follow alphabetical order." In the `levels(murders$region)` example above however, the levels are clearly **not** in alphabetical order. To avoid confusion, the text should explain that the data set `murders` as shown in the example has already been ordered in a different way.

**Comment by rafalab** [comment]
Good catch! I changed the paragraph to explain this better:

"Note that the levels have an order that is different from the order of appearance in the factor object. The default in R is for the levels to follow alphabetical order. However, often we want the levels to follow a different order. You can specify an order through the `levels` argument when creating the factor with the `factor` function. For example, in the murders dataset regions are ordered from east to west.  The function `reorder` lets us change the order of the levels of a factor variable based on a summary computed on a numeric vector. We will demonstrate this with a simple example, and will see more advanced ones in the Data Visualization part of the book. "
