### ISSUE TITLE
A doubt in Section 27.4.5

### ISSUE THREAD

**Issue by ThenoobMario** [rafalab/dsbook#116]
I am a little confused in this section where we try to resolve the confusion matrix with F1 Score. There is a discrepancy in the value found in best_cutoff and the value considered (best_cutoff = 66 and the value written = 65). And this wouldn't be an issue but the code after it has taken best_cutoff as it is. It would be helpful to know which one is correct.

**Comment by rafalab** [comment]
Thanks for catching this. 66 is the correct one. I changed the book so that code is used to get the number rather than writing it in.
