### ISSUE TITLE
Smoother in second plot 28.3.2 not shown 

### ISSUE THREAD

**Issue by tmms1** [rafalab/dsbook#117]
The smoother in the second plot in section 28.3.2 "Beware of default smoothing parameters" is not visible. 

Running the code to reproduce the figure 

`polls_2008 %>% ggplot(aes(day, margin)) +
  geom_point() + 
  geom_smooth()`

resulted in this error:

geom_smooth() using formula 'y ~ x'
Warning message:
Computation failed in `stat_smooth()`:
'what' must be a function or character string

**Comment by rafalab** [comment]
Thanks for catching this. It seems there error came from the next line in which we change the method arguments. It seem with new version of ggplot we need to specific which method we are using. The code is now

```
polls_2008 %>% ggplot(aes(day, margin)) +
  geom_point() + 
  geom_smooth(method = "loess", span = 0.15, method.args = list(degree=1))
```
