### ISSUE TITLE
Chapter 2.4.6 Lists example

### ISSUE THREAD

**Issue by atraxler** [rafalab/dsbook#119]
https://github.com/rafalab/dsbook/blob/6ec8eaf37de6081e07a4e0e4071b6ea0e8a289f0/R/R-basics.Rmd#L531-L536

I was curious, should `echo=FALSE` be removed from this block? Currently it hides the definition of the example list object `record`, which makes the next lines (inspecting the object, accessing elements of it, etc.) not work.

**Comment by rafalab** [comment]
I changed the entire section based on this comment. Thanks.
