### ISSUE TITLE
MNIST dataset (Section 27.3)

### ISSUE THREAD

**Issue by aidanhorn** [rafalab/dsbook#121]
The MNIST data in `dslabs_0.7.3` is stored under the object `mnist_27`. Section 27.3 in the book gets this wrong, when it asks the reader to use `mnist`. Furthermore, the name of the outcome vector is now `y`, not `labels`. The data I get for `y[5]` and `y[6]` in the example further down also seems to be different (the numerals 7 and 2 respectively).

**Comment by rafalab** [comment]
Thanks for catching this. The code has been updated to:

```
library(dslabs)
mnist <- read_mnist()
y <- mnist$train$labels
```
