### ISSUE TITLE
Mistake in 33.9.2 formulas?

### ISSUE THREAD

**Issue by wycheong** [rafalab/dsbook#123]
In ml/recommendation-systems.Rmd lines 430 or 434 (section 33.9.2), are there Ns missing?

I believe line 430 should be $$ \frac{1}{N}\sum_{u,i} \left(y_{u,i} - \mu - b_i\right)^2 + \frac{\lambda}{N} \sum_{i} b_i^2 $$ or line 434 should be $$ \frac{1}{N\lambda + n_i} \sum_{u=1}^{n_i} \left(Y_{u,i} - \hat{\mu}\right) $$.

**Comment by rafalab** [comment]
Are you looking at the pdf or the html? I recently fixed this but it will only show up in the html and Rmd.
