### ISSUE TITLE
Misplaced filter() call in ch. 33 user effect plot

### ISSUE THREAD

**Issue by ryan-heslin** [rafalab/dsbook#129]
I think the summarize() and filter() calls in the below code (from 33.7.6) are out of order. The intent is to filter for users with more than 100 ratings, but filtering after summarizing does nothing because summarize automatically ungroups the dataframe, so n() is equal to the number of rows.
```
train_set %>% 
  group_by(userId) %>% 
  summarize(b_u = mean(rating)) %>% 
  filter(n()  >=100) %>%
  ggplot(aes(b_u)) + 
  geom_histogram(bins = 30, color = "black")
```
Filtering between the group_by and summarize achieves the intended purpose:
```
train_set %>% 
  group_by(userId) %>% 
  filter(n() >=100) %>%
  summarize(b_u = mean(rating)) %>% 
  ggplot(aes(b_u)) + 
  geom_histogram(bins = 30, color = "black")
```
One other thing: the text says to filter for users with over 100 ratings, but the code uses >= 100.

**Comment by rafalab** [comment]
Thanks! This is fixed now.

**Comment by ryan-heslin** [comment]
No problem.
