### ISSUE TITLE
On POSIX filenames are case-sensitive

### ISSUE THREAD

**Issue by raffaem** [rafalab/dsbook#130]
I am trying to compile the book into a PDF and i'm getting the following error:

'``
Quitting from lines 258-259 (book.Rmd) 
Error in knitr::include_graphics(file.path(img_path, "RStudio.png")) : 
  Cannot find the file(s): "R/img/RStudio.png"
```

That file, in fact, is called "rstudio.png" and not "RStudio.png"

**Comment by rafalab** [comment]
This is fixed. Thanks.
