### ISSUE TITLE
Cannot compile: R asks for user input

### ISSUE THREAD

**Issue by raffaem** [rafalab/dsbook#131]
I am trying to compile a PDF book by running:

```
bookdown::render_book("index.Rmd", "bookdown::pdf_book")
```

But the process gets stuck. In particular, at `unnamed-chunk-976`, R prints "Selection" and asks for user input. Whatever the user input, the "Selection" prompt is displayed again:

```
label: unnamed-chunk-976
Selection: sadasdasd
```

**Comment by raffaem** [comment]
Ok the problem is in `book.Rmd` at line 16870, which states:

```
get_sentiments("loughran") %>% count(sentiment)
```

This gives the following output:

```
Do you want to download:
 Name: Loughran-McDonald Sentiment lexicon 
 URL: https://sraf.nd.edu/textual-analysis/resources/ 
 License: License required for commercial use. Please contact tloughra@nd.edu. 
 Size: 6.7 MB (cleaned 142 KB) 
 Download mechanism: https 

1: Yes
2: No

Selection: 1
trying URL 'https://drive.google.com/uc?id=12ECPJMxV2wSalXG8ykMmkpa1fq_ur0Rf&export=download'
```

But only "Selection:" (the last line) is shown when you compile the book

**Comment by raffaem** [comment]
Anyway, if you press `1`, it doesn't work, because the URL it tries to download (`https://drive.google.com/uc?id=12ECPJMxV2wSalXG8ykMmkpa1fq_ur0Rf&export=download`) returns 404.

If you press `2`  it doesn't work because it gives:

```
Selection: 2
Quitting from lines 16870-16871 (book.Rmd) 
Error in UseMethod("count") : 
  no applicable method for 'count' applied to an object of class "NULL"
```

So there is no way to complete the compilation

**Comment by raffaem** [comment]
Ok so pressing "1" will let the compilation continue.

But there is another of this thing at lines 19374-19379 (book.Rmd)

**Comment by rafalab** [comment]
Compiling works better if you install all the packages first. This [R markdown](https://github.com/rafalab/dsbook/blob/master/install-libraries.Rmd)  helps with this:

**Comment by raffaem** [comment]
Thank you.

Were I supposed to find that file on my own?

Can we add a "compile" section to `README.md` that points to that file?

**Comment by rafalab** [comment]
The REAMDE.md file includes this: 

> The install-libraries.Rmd, contributed by Emmanuel-R8 installs all the libraries needed to have all chapters of the book run on your computer.

Is there something you recommend adding that would make it clearer?
