### ISSUE TITLE
how to download libraries for exmaples

### ISSUE THREAD

**Issue by kurdig** [rafalab/dsbook#140]
how do i get murder dataset on my rstudio. the instructions in the book, do not work yet. 
library(dslabs)
data(murders)

secondly, the instruction on github says "The install-libraries.Rmd, contributed by Emmanuel-R8 installs all the libraries needed to have all chapters of the book run on your computer."
Where do i get this rmd file? how do i install it! Will appreciate some instructions for folks new to coding!!

**Comment by rafalab** [comment]
What error message do you get? Most likely error is that dslabs is not inalled. `install.packages("dslabs")` should do it.

**Comment by kurdig** [comment]
I worked after it finished installing in some time.
