### ISSUE TITLE
Problem solving the exercise 6 in 2.10 section

### ISSUE THREAD

**Issue by Emiliano-Juarez** [rafalab/dsbook#142]
Hi there! 👋🏼
First of all, I want to thank for this book, its a great tool to practice the skills and the best part its available in two languages.

I just want to ask for help in the exercise 6, specifically on 2.10 section, therefore that I want to get the states ordered based on their population but in increasing way, it means Wyoming the first row as a consequence California as last one. So I executed the below code but its disordered

`my_df <- data.frame(states = murders$state, pop.ranks = ranks)`

**Note:** You gave a hint, which was we need to assign the ranks in a variable named `ind` and then use `[brackets]` I made it but it did not give me what I wish. Can someone share a me piece of advice please?

Thanks in advanced.

**Comment by jmtruffa** [comment]
Have you tried to use tidyverse?

murders %>% arrange(population)
