### ISSUE TITLE
15.11.1 Interest rates explained with chance model - 50% chances of Breakeven

### ISSUE THREAD

**Issue by jmtruffa** [rafalab/dsbook#143]
Great book and a great initiative to make it available for free. 

After computing the interest rate to offset possible losses arising from the foreclosure of the 2% default in the portfolio of mortgage loans:

"However, we still have a problem. Although this interest rate guarantees that on average we break even, there is a 50% chance that we lose money."

Where does this 50% chance come from?

Thanks in advance,

**Comment by rafalab** [comment]
I believe in the latest version the number is 35%. This comes runnign a simulation and observing that for 35% of the simulations, the profit was negative. The key line is this:

```
mean(profit<0)
```
