### ISSUE TITLE
15.9 valores-p

### ISSUE THREAD

**Issue by jmtruffa** [rafalab/dsbook#144]
Una duda respecto a ese punto del capítulo 15.

En la explicación de los valores-p, estableciendo a 2p - 1 = 0, me surge la duda en cuanto al cálculo del valor-p hecho como  Pr(| $\bar X$ - 0.5| > 0.02). No debería ser 0.04 en lugar de 0.02, dado que viene del ejemplo donde obtuvo como muestra 0.52 de cuentas azules (y eso supone una diferencia de 0.04)

Gracias. Excelente material. Lo estoy leyendo detenidamente.

**Comment by rafalab** [comment]
Nota que $|\bar{X} - 0.5| > 0.2 \implies 2|\bar{X} - 0.5| > 0.4 \implies |2\bar{X} - 1| > 0.4$

Pero debo cambiar la explicación para que esté más claro.
