### ISSUE TITLE
22.4 Exercise 1 (2.2 Question 5)

### ISSUE THREAD

**Issue by pauluhn** [rafalab/dsbook#150]
In the book, [22.4](http://rafalab.dfci.harvard.edu/dsbook/joining-tables.html#exercises-42) exercise 1 refers to data `Master` which cannot be found. 

It should be corrected to `People` which was found on EdX's [Section 2: Tidy Data](https://learning.edx.org/course/course-v1:HarvardX+PH125.6x+1T2023/block-v1:HarvardX+PH125.6x+1T2023+type@sequential+block@0b01a6742500451196b76f724ac39168) / [2.2: Combining Tables](https://learning.edx.org/course/course-v1:HarvardX+PH125.6x+1T2023/block-v1:HarvardX+PH125.6x+1T2023+type@sequential+block@11deefe5511a468cb74905ba9df081e0) / Introduction to Questions 5-7

**Comment by rafalab** [comment]
Thanks! Just fixed it. It should show up next time the html for the book gets updated. Thanks!
