### ISSUE TITLE
Code doesn't show up in book

### ISSUE THREAD

**Issue by pauluhn** [rafalab/dsbook#154]
https://github.com/rafalab/dsbook/blob/74f8c021db5286bd116acbb2c79596319f5e82a0/regression/linear-models.Rmd#L80

http://rafalab.dfci.harvard.edu/dsbook/linear-models.html#understanding-confounding-through-stratification

![Screenshot 2023-08-18 at 10 07 23 PM](https://github.com/rafalab/dsbook/assets/6515165/ae5517a1-f673-4a6b-b98c-13dab7bab26c)

**Comment by rafalab** [comment]
This should be fixed now.
