### ISSUE TITLE
Discrepancies between .Rmd and .html, rules for contribution

### ISSUE THREAD

**Issue by gillsignals** [rafalab/dsbook#19]
There are discrepancies in the .Rmd and .html bookdown pages. The ones I have found relate to typos that look like they still need to be corrected in the book but have been fixed in the code.

Compare "accountfor" at the end of the second paragraph of this section: https://rafalab.github.io/dsbook/linear-models.html

and corresponding R markdown:
https://github.com/rafalab/dsbook/blob/ea9c29f7d0b61b7e3716a81e66609ee09f37332d/regression/linear-models.Rmd#L154

I will try to open a pull request to resolve this by running knit on edited files and putting the knit files in the directory currently holding the html files. However, I have never built something in bookdown, learned Git mostly through this course, and there is no contributing guide for the project. Any guidance would be appreciated.

**Comment by gillsignals** [comment]
I ran into issues quickly - several sections will not individually knit because they rely on objects defined in earlier sections (i.e. https://github.com/rafalab/dsbook/blob/ea9c29f7d0b61b7e3716a81e66609ee09f37332d/R/basic-data-wrangling.Rmd#L18 relies on library(dslabs) and data(murders) but that is not defined in this .Rmd).

This is a common occurrence and a routine topic in course discussions is that it can be difficult to work with these .Rmd docs individually when they don't internally define required packages and objects.

As necessary, I will add code boxes to the very top of each doc to define required packages . If this is not compatible with your desired book style you can certainly choose to omit, but this is an unmet student need.

**Comment by gillsignals** [comment]
Thanks! That makes sense about files not running individually, and it also seems totally reasonable to minimize repetition of package listing.

Having said that, there are repeated comments on the course message boards from students who download individual Rmds and then have difficulty identifying which packages are necessary, so it might still be helpful to list packages more frequently.

**Comment by rafalab** [comment]
I will look into improving this. Thanks for pointing out the problem.

**Comment by rafalab** [comment]
I think this is fixed now. You should only need to load dplyr and dslabs for the Rmds to run. If not, please point me to specific Rmds in which this is not the case.
