### ISSUE TITLE
fiftystater package no longer supported

### ISSUE THREAD

**Issue by gillsignals** [rafalab/dsbook#20]
https://github.com/rafalab/dsbook/blob/ea9c29f7d0b61b7e3716a81e66609ee09f37332d/R/motivation.Rmd#L31

The "fiftystater" package was removed from the CRAN repository as of 2018-10-10. 
https://cran.r-project.org/web/packages/fiftystater/index.html

**Comment by rafalab** [comment]
Thanks! I will try to find a way to avoid using this package.

**Comment by rafalab** [comment]
I removed the dependence on this package. thanks for point this out.
