### ISSUE TITLE
Typo Chapter 4, Section 4.5

### ISSUE THREAD

**Issue by jethroppaPH** [rafalab/dsbook#24]
In the subsection "**4.5 Variable names**", second sentence of the first paragraph:

"Some basic rules in R is that they have to start with a letter, can’t contain spaces and should be variables that are predefined in R."

I guess it should be:

"Some basic rules in R is that they have to start with a letter, can’t contain spaces and should **not** be variables that are predefined in R."

**Comment by rafalab** [comment]
Thanks!

**Comment by gillsignals** [comment]
Issue was fixed but not closed.
