### ISSUE TITLE
trump_tweets

### ISSUE THREAD

**Issue by elibre82** [rafalab/dsbook#48]
Hello,

I tried to compile the code on R studio to generate a book, but I get the same error each time:
Quitting from lines 13757-13758 (book.Rmd) 
Error in eval(expr, envir, enclos) : objet 'trump_tweets' introuvable
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
De plus : There were 18 warnings (use warnings() to see them)

Arnaud

**Comment by gillsignals** [comment]
Can't replicate this error. The book compiles okay for Rafa, and the document runs and knits for me. `trump_tweets` is properly defined throughout the document, and if "introuvable" does indeed translate in English to "not found" then this error is no longer applicable. Perhaps it applied to an earlier version of the book.

Please let us know if this still throws an error, but the issue may have been resolved over the last couple months by other edits. Thanks!
