### ISSUE TITLE
Chapter 68: Test from $train or $test ?

### ISSUE THREAD

**Issue by gwierzchowski** [rafalab/dsbook#53]
I'm not sure if this is on purpose or typo.
At very beginning of Chapter 68 there is code:
```r
set.seed(123)
index <- sample(nrow(mnist$train$images), 10000)
x <- mnist$train$images[index,]
y <- factor(mnist$train$labels[index])

index <- sample(nrow(mnist$train$images), 1000)
x_test <- mnist$train$images[index,]
y_test <- factor(mnist$train$labels[index])
```
I'm not sure if instructions in second group maybe should use `mnist$test`?

**Comment by dedelman04** [comment]
Additionally, when fitting with the entire model, the text says to use k = 5, when k = 3 is shown to have the most accuracy based on the training:

`fit_knn<- knn3(x[ ,col_index], y,  k = 5)`

(also a comma in y[index, ] in the n, b code sample to test out the model training should be outside the brackets)

**Comment by gillsignals** [comment]
Both issues have been addressed. @dedelman04 - next time it would be best if you open a new issue for a separate problem. Thanks!
