### ISSUE TITLE
Chapter 70: `lim` variable undefined

### ISSUE THREAD

**Issue by gwierzchowski** [rafalab/dsbook#55]
The code from ch 70.1:
```r
rafalib::mypar()
plot(z, xlim=lim, ylim = lim - mean(lim))
```
cannot be run because variable `lim` in not defined.
Adding line:
```r
lim <- c(min(z[,1]) - 1, max(z[,1]) + 1)
```
does the trick.

**Comment by gillsignals** [comment]
The current version of the book has:

`lim <- c(48, 78)`

in that block of code. Thanks!
