### ISSUE TITLE
§66.6 typo and reference to a numbered figure when figures are unnumbered

### ISSUE THREAD

**Issue by technocrat** [rafalab/dsbook#56]
Too minor for a pull request

> The actuary is:

should be 

The **Accuracy** is:

and in Exercise 5 reference is made to "figure 3," but figures are unnumbered.

BTW: As the series has gotten progressively into new territory for me, I cloned this repository to be able to cut and paste the code examples (and a few hidden in chunks) to run the code. That way, when a snippet appears in the lectures, I can pause and run it to see in better detail what you're conveying. Students who are not familiar with github would benefit by having a facility to download the code snippets with any required libraries in a file per video segment.

**Comment by gillsignals** [comment]
Issue has been fixed. I will bring up the code download suggestion with Rafa.
