### ISSUE TITLE
Typo in Ch 2 (2.4.1)

### ISSUE THREAD

**Issue by defeit** [rafalab/dsbook#76]
Version 2019-03-17: Description on page 30 of RStudio panes and tabs says "On the right, the top pane includes three tabs: Extensions, History and Connections..." The image at top of the next page shows these as "Environment," "History," and "Connections." "Environment" appears in my recently downloaded Windows version of RStudio as well. "Extension" should be changed to "Environment."

**Comment by rafalab** [comment]
Fixed. Thanks!
