### ISSUE TITLE
Typo in chapter 15.10

### ISSUE THREAD

**Issue by JamesHaughey** [rafalab/dsbook#80]
Question 14 in the exercises asks "What is the standard error of S?" The previous two questions refer to Y and this question has already been asked in question 7. I think this should read "What is the standard error of Y?".
![image](https://user-images.githubusercontent.com/39332783/56853093-0f1b6d80-691b-11e9-9cd1-94ccea78755a.png)

**Comment by rafalab** [comment]
This will be fixed the next time I push changes. Thanks for point this out.
