### ISSUE TITLE
getting-started.Rmd screenshot error

### ISSUE THREAD

**Issue by gillsignals** [rafalab/dsbook#84]
There is a typo in the screenshot just below this sentence:

"You can also use the key binding: Ctrl+Shift+Enter on Windows or command+shift+return on the Mac."

The code in the screenshot says `geom_points` instead of `geom_point`. It confused some people who were trying to code along.

A smaller note for this chapter - some people are trying to code along and we haven't yet explained that you need to install packages like tidyverse and dslabs before using them. Might help to add a passing reference to the following section, https://rafalab.github.io/dsbook/getting-started.html#installing-r-packages.

**Comment by rafalab** [comment]
Thanks. This was fixed sometime ago but I forgot to close this.
