### ISSUE TITLE
14.5.1 Multiplication rule

### ISSUE THREAD

**Issue by Dean-Webb** [rafalab/dsbook#88]
In the study material, the likelihood of an Ace followed by a face card is given as 
1/13×**12/52**≈0.02

The video mentioned that 10's can also be included and that given that the ace is already removed the last section should be divided by 51. Which give you 
1/13×**16/51**≈0.02

I think the guide should be corrected?

**Comment by rafalab** [comment]
Thanks! Nice catch. I've fixed the Rmd. The fix will show up on the html next time I update the book.
