### ISSUE TITLE
Typo in Chapter 16.8: Power

### ISSUE THREAD

**Issue by mohayusuf** [rafalab/dsbook#89]
Hello,

There appears to be a small typo in the calculation for the confidence intervals for the spread. 

I believe it should read as follows:

> N <- 25
> x_hat <- 0.48
> (**2 * x_hat - 1**) + c(-1.96, 1.96) * 2 * sqrt(x_hat * (1 - x_hat) / **N**)
[1] -0.4316863  0.3516863

Excellent introductory book to R; thank you!

Regards,
Mohamed

**Comment by rafalab** [comment]
Thanks! Good catch. It will be fixed the next time I update the book.
