### ISSUE TITLE
Ch 14 .11 - typo?

### ISSUE THREAD

**Issue by jimrothstein** [rafalab/dsbook#92]
"We say that a random quantity is normally distributed with average m and standard deviation s if its probability distribution is defined by:

```{r}
F(a) = rnorm(a, m, s)
```

====
Should it be **p**norm?
Propose:

```{r}
F(a) = pnorm(a, m, s)
```

**Comment by rafalab** [comment]
Yes, it is now `pnorm`. Thanks.
