### ISSUE TITLE
Version of PDF on Leanpub is out of date (2019-05-02)

### ISSUE THREAD

**Issue by nelsonic** [rafalab/dsbook#94]
Hi @rafalab really excited to be joining your course on [edX](https://online-learning.harvard.edu/course/data-science-machine-learning) 👍 
I just downloaded the PDF of the book from Leanpub https://leanpub.com/datasciencebook
And the PDF **`2019-05-01`**
![image](https://user-images.githubusercontent.com/194400/67977725-86a2c000-fc10-11e9-99c5-8b0a56026692.png)

and the site say that it was **`LAST UPDATED ON 2019-05-02`**
<img width="1155" alt="datascience-leanpub-book" src="https://user-images.githubusercontent.com/194400/67977674-71c62c80-fc10-11e9-8836-f812944ae2c1.png">

Meanwhile the HTML version https://rafalab.github.io/dsbook was last updated **`2019-10-25`**:
<img width="1121" alt="datascience-book-last-updated-2019-10-25" src="https://user-images.githubusercontent.com/194400/67977882-d84b4a80-fc10-11e9-8586-b1161d38b37a.png">

It appears that new versions merged into `master` on GitHub 
are not being automatically published to the PDF version on Leanpub. 
# 💭

**Comment by rafalab** [comment]
Updated.

**Comment by nelsonic** [comment]
@rafalab thanks for the quick response. ⚡️ 
![data-science-book-updated](https://user-images.githubusercontent.com/194400/68043882-37bb6000-fcce-11e9-93cd-5210fd8700c9.png)

Update confirmed. 👍
