### ISSUE TITLE
Section 8.15 Exercises: Question 15 should cite to question 10 (?) instead of question 3

### ISSUE THREAD

**Issue by tuanchauict** [rafalab/dsbook#98]
In option c and d of question 15:
`As seen in question 3, ...`

Question 3 in the book is about a plot image `Study the following boxplots showing population sizes by country:`
while question 10 is related to normal distribution vs real data:
> Notice that the approximation calculated in question two is very close to the exact calculation in the first question. Now perform the same task for more extreme values. Compare the exact calculation and the normal approximation for the interval (79,81]. How many times bigger is the actual proportion than the approximation?

**Comment by rafalab** [comment]
Thanks. This is fixed now.
